# Generated by Django 4.1.6 on 2023-02-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
