# Generated by Django 4.1.6 on 2023-03-01 14:10

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_delete_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='video',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' ', verbose_name='Video'),
            preserve_default=False,
        ),
    ]
