# Generated by Django 4.1.6 on 2023-03-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0004_entry_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='video',
            field=models.URLField(),
        ),
    ]
