# Generated by Django 4.1.7 on 2023-03-03 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('league', models.CharField(max_length=50, verbose_name='Liga')),
                ('front_page', models.ImageField(upload_to='coutas', verbose_name='portada')),
                ('public', models.BooleanField(default=True, verbose_name='Avtivo')),
                ('slug', models.SlugField(editable=False, max_length=300)),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('locals', models.CharField(max_length=30, verbose_name='Local')),
                ('local_quote', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cuota del Local')),
                ('image_locals', models.ImageField(upload_to='coutas', verbose_name='escudo Local')),
                ('visitors', models.CharField(max_length=30, verbose_name='Visitantes')),
                ('visitor_quote', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cuota del Visitante')),
                ('image_visitors', models.ImageField(upload_to='coutas', verbose_name='Escudo visitante')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.league')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
            },
        ),
    ]
