# Generated by Django 4.1.6 on 2023-02-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Avtivo'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='slug',
            field=models.SlugField(default='-', editable=False, max_length=300),
            preserve_default=False,
        ),
    ]
