# Generated by Django 4.1.6 on 2023-02-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_league_public_quotes_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='Visitor_quote',
            new_name='visitor_quote',
        ),
    ]
