# Generated by Django 4.1.6 on 2023-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_rename_visitor_quote_quotes_visitor_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='slug',
        ),
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='-', editable=False, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='image_locals',
            field=models.ImageField(default='-', upload_to='coutas', verbose_name='escudo Local'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='image_visitors',
            field=models.ImageField(default='-', upload_to='coutas', verbose_name='Escudo visitante'),
            preserve_default=False,
        ),
    ]
